# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7_with_system_site_packages"

before_install:
  - cd test
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - git checkout tags/0.7.11
  - make
  - cd ..
  - PATH=`pwd`/bwa:$PATH
  - git clone https://github.com/samtools/htslib.git
  - cd htslib
  - git checkout tags/1.3
  - make
  - cd ..
  - git clone https://github.com/samtools/samtools.git
  - cd samtools
  - git checkout tags/1.3
  - make
  - cd ..
  - PATH=`pwd`/samtools/bin:$PATH
  - cd ..

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
    cd test && nosetests --exe -v